name: Build and deploy

on:
  push:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSSWORD}}

      - name: Build and push web image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.fe
          push: true
          tag: devnick10/docker-cicd-web:latest
          build-args: |
           DATABASE_URL=${{secrets.DATABASE_URL}}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.http
          push: true
          tag: devnick10/docker-cicd-http:latest

      - name: Build and push websocket image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tag: devnick10/docker-cicd-ws:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull devnick10/docker-cicd-web:latest
            sudo docker stop docker-cicd-web || true
            sudo docker rm docker-cicd-web || true
            sudo docker run -e DATABASE_URL ${{secrets.DATABASE_URL}} -d --name web -p 3000:3000 devnick10/docker-cicd-web:latest
            